baseurl = "/"
languageCode = "en-us"
title = "blog"
theme = "kiss"
copyright = "&copy; <a href=\"https://home.cern/\">CERN</a> 2024"
Paginate = 5
enableRobotsTXT = true
pygmentsUseClasses = true

[params.rss]
includeContent = true

[params.info]
homeTitle = "REANA blog"
codeCopy = true
taxonomiesCount = true

[params.assets]
customCSS = ["/css/custom.css", "css/syntax.css"]

[params.social]
twitter = "reanahub"
github = "reanahub"
email = "reana-team@cern.ch"
rss = "index.xml"

[params.social.config]
platforms = ["github", "twitter", "email"]

[params.sections_right]
